Restaurant/Restaurant.WebUI/Controllers/HakkimizdaController.cs
using Restaurant.Entity.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Restaurant.WebUI.Controllers
{
    
    public class HakkimizdaController : Controller
    {
        private RestaurantDBContext db = new RestaurantDBContext();
        // GET: About
        public ActionResult Index()
        {
            ViewBag.Seo = db.MainGoogleSeos.Where(x => x.IsActive == true && x.PageUrl == "Hakkımızda").FirstOrDefault();
            return View(db.Abouts.Where(x=>x.IsActive==true && x.Title== "Bizim Hakkımızda").FirstOrDefault());
        }
        #region Sayfalar

        #endregion
        #region ParçalıSayfalar
        public ActionResult PartialHakkimizdaConstantValue()
        {
            var a = db.ConstantValues.Where(x => x.IsActive == true && x.Code == "Hakkımızda|Banner").FirstOrDefault();
            return PartialView(a);
        }
        #endregion
    }
}

Restaurant/Restaurant.WebUI/Views/Hakkimizda/Index.cshtml
@model Restaurant.Entity.Entity.About
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{Html.RenderAction("PartialHakkimizdaConstantValue", "Hakkimizda");}
<section class="inner-section about-company">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6">
                <div class="about-content">
                    @if (Model.Title == "Bizim Hakkımızda")
                    {
                        <h2 title="Hakkımızda">Hakkımızda</h2>
                    }
                    <p title="@Html.Raw(Model.ShortDescription)">
                        @Html.Raw(Model.Description)
                    </p>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="about-img">
                    <img src="~/File/Abouts/@Model.File" alt="@Model.Title">
                </div>
            </div>
        </div>
    </div>
</section>

Restaurant/Restaurant.WebUI/Views/Hakkimizda/PartialHakkimizdaConstantValue.cshtml
@model Restaurant.Entity.Entity.ConstantValue
<section class="inner-section single-banner" style="background-image: url(/File/ConstantValuess/@Model.ImageUrl)">
</section>