Restaurant/Restaurant.WebUI/Controllers/SıkcaSorulanSorularController.cs
using Restaurant.Entity.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Restaurant.WebUI.Controllers
{
    public class SıkcaSorulanSorularController : Controller
    {
        RestaurantDBContext db = new RestaurantDBContext();
        // GET: SıkcaSorulanSorular
        public ActionResult Index()
        {
            ViewBag.Seo = db.MainGoogleSeos.Where(x => x.IsActive == true && x.PageUrl == "Sıkça Sorulan Sorular").FirstOrDefault();
            return View(db.SSS.Where(x => x.IsActive == true).ToList().OrderBy(x=>x.Rank));
        }
        #region ParçalıSayfalar
        public ActionResult PartialSSSConstantValue()
        {
            var a = db.ConstantValues.Where(x => x.IsActive == true && x.Code == "SSS|Banner").FirstOrDefault();
            return PartialView(a);
        }
        #endregion
    }
}

Restaurant/Restaurant.WebUI/Views/SıkcaSorulanSorular/Index.cshtml
@model IEnumerable<Restaurant.Entity.Entity.SSS>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{Html.RenderAction("PartialSSSConstantValue", "SıkcaSorulanSorular");}
<section class="inner-section faq-part">
    <div class="container">
        <div class="col-lg-12">
            <div class="section-heading">
                <h2>Sıkça Sorulan Sorular</h2>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-12 mx-auto">
                <div class="faq-parent">
                    @foreach (var item in Model)
                    {
                        <div class="faq-child">
                            <div class="faq-que"><button>@item.Tittle</button></div>
                            <div class="faq-ans">
                                <div class="row">
                                    <div class="col-md-9">
                                        <p class="yazi">
                                            @Html.Raw(item.Content)
                                        </p>
                                    </div>
                                    <div class="col-md-3">
                                        <img class="sss" src="~/File/SSSs/@item.File"  alt="@item.Tittle"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>
<style>
    .sss{
        width:100%;
    }
</style>

Restaurant/Restaurant.WebUI/Views/SıkcaSorulanSorular/PartialSSSConstantValue.cshtml
@model Restaurant.Entity.Entity.ConstantValue
<section class="inner-section single-banner" style="background-image: url(/File/ConstantValuess/@Model.ImageUrl)">
</section>