Restaurant/Restaurant.WebUI/Controllers/HaberDetayController.cs
using Restaurant.Entity.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Restaurant.WebUI.Controllers
{
    public class HaberDetayController : Controller
    {
        RestaurantDBContext db = new RestaurantDBContext();
        // GET: HaberDetay
        public ActionResult Index(string s)
        {
            ViewBag.Seo = db.News.Where(x => x.Slug == s).FirstOrDefault();
            return View(db.News.Where(x => x.IsActive == true && x.Slug == s).FirstOrDefault());
        }
        #region ParçalıSayfalar
        public ActionResult PartialHaberDetayConstantValue()
        {
            var a = db.ConstantValues.Where(x => x.IsActive == true && x.Code == "Haber Detay|Banner").FirstOrDefault();
            return PartialView(a);
        }
        public ActionResult PartialRandomNewsList()
        {
            return PartialView(db.News.OrderBy(x => Guid.NewGuid()).Where(x => x.IsActive == true).Take(5).ToList());
        }
        #endregion
    }
}

Restaurant/Restaurant.WebUI/Views/HaberDetay/Index.cshtml
@model Restaurant.Entity.Entity.News
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{Html.RenderAction("PartialHaberDetayConstantValue", "HaberDetay");}
<section class="inner-section blog-standard">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-7">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="blog-card">
                            <div class="blog-media">
                                <a class="blog-img">
                                    @if (Model.File.EndsWith(".PNG") || Model.File.EndsWith(".JPG") || Model.File.EndsWith(".JPEG") || Model.File.EndsWith(".GIF") || Model.File.EndsWith(".TIFF") || Model.File.EndsWith(".jpg") || Model.File.EndsWith(".png") || Model.File.EndsWith(".jpeg") || Model.File.EndsWith(".tiff") || Model.File.EndsWith(".gif"))
                                    {
                                        <img src="~/File/News/@Model.File"
                                             alt="blog" width="100%">
                                    }
                                    else if (Model.File.EndsWith(".avi") || Model.File.EndsWith(".AVI") || Model.File.EndsWith(".mp4") || Model.File.EndsWith(".MP4") || Model.File.EndsWith(".mov") || Model.File.EndsWith(".MOV") || Model.File.EndsWith(".flv") || Model.File.EndsWith(".FLV") || Model.File.EndsWith(".mpg") || Model.File.EndsWith(".MPG") || Model.File.EndsWith(".mkv") || Model.File.EndsWith(".MKV"))
                                    {
                                        <video controls>
                                            <source src="~/File/News/@Model.File" type="video/mp4">
                                        </video>
                                    }
                                </a>
                            </div>
                            <div class="blog-content">
                                <h4 class="blog-title">
                                    @Model.Title
                                </h4>
                                <p class="blog-desc">
                                    @Html.Raw(Model.Content)
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-10 col-md-7 col-lg-5">
                <div class="blog-widget">
                    <h3 class="blog-widget-title" title="Doybox Haberler">Haberlerimiz</h3>
                    <ul class="blog-widget-feed">
                        @{Html.RenderAction("PartialRandomNewsList", "HaberDetay");}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

Restaurant/Restaurant.WebUI/Views/HaberDetay/PartialHaberDetayConstantValue.cshtml
@model Restaurant.Entity.Entity.ConstantValue
<section class="inner-section single-banner" style="background-image: url(/File/ConstantValuess/@Model.ImageUrl)">
</section>

Restaurant/Restaurant.WebUI/Views/HaberDetay/PartialRandomNewsList.cshtml
@model IEnumerable<Restaurant.Entity.Entity.News>
@foreach (var item in Model)
{
    <li>
        <a class="blog-widget-media" href="/haberler/@item.Slug">
            @if (item.File.EndsWith(".PNG") || item.File.EndsWith(".JPG") || item.File.EndsWith(".JPEG") || item.File.EndsWith(".GIF") || item.File.EndsWith(".TIFF") || item.File.EndsWith(".jpg") || item.File.EndsWith(".png") || item.File.EndsWith(".jpeg") || item.File.EndsWith(".tiff") || item.File.EndsWith(".gif"))
            {
                <img src="~/File/News/@item.File"
                     alt="@item.Title">
            }
            else if (item.File.EndsWith(".avi") || item.File.EndsWith(".AVI") || item.File.EndsWith(".mp4") || item.File.EndsWith(".MP4") || item.File.EndsWith(".mov") || item.File.EndsWith(".MOV") || item.File.EndsWith(".flv") || item.File.EndsWith(".FLV") || item.File.EndsWith(".mpg") || item.File.EndsWith(".MPG") || item.File.EndsWith(".mkv") || item.File.EndsWith(".MKV"))
            {
                <video controls autoplay muted>
                    <source src="~/File/News/@item.File" type="video/mp4">
                </video>
            }
        </a>
        <h6 class="blog-widget-text">
            <a href="/haberler/@item.Slug">
                @item.Title
            </a>
        </h6>
    </li>
}